version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment: 
      - MYSQL_DATABASE=xxx
      - MYSQL_ROOT_PASSWORD=xxx
    ports:
      - '3306:3306'
    expose:
      - 3306
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
    ports:
      - 8080:8080

# docker compose -p estudy-nodejs-mysql up -d 