version: "3.8"
services:
  nginx:
    build: 
      context: .
    ports:
      - 80:80
    volumes:
      - ../../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
# docker compose -p estudy-nginx up -d