version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment: 
      - MYSQL_DATABASE=xxx
      - MYSQL_ROOT_PASSWORD=xxx
    ports:
      - '3306:3306'
    expose:
      - 3306
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - URL_REACT=http://localhost
    ports:
      - 8081:8081
    expose:
      - 8081
  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p estudy up -d